name: happypose-det
channels:
   - conda-forge
   - pytorch
   - nvidia
   - anaconda
   - defaults
dependencies:
  - nvidia::cudatoolkit==11.3.1
  - python=3.9
  - pip
  - pytorch::pytorch==1.11.0
  - torchvision==0.12.0
  - mkl==2024.0.0
  - geckodriver
  - firefox
  - opencv
  - pinocchio
  - pip:
      - blenderproc==2.6.2
      - git+https://github.com/agimus-project/happypose@dev
